wm-support = "none";
animations = true;
animation-stiffness = 600;
animation-window-mass = 1;
animation-dampening = 48;
animation-clamping = false;
animation-for-open-window = "slide-up";
animation-for-unmap-window = "slide-down";
corner-radius = 5
corners-rule = [
  "0:class_g    = 'Polybar'",
];
fading = true;
fade-in-step = 1;
fade-out-step = 1;
inactive-opacity = 1;
frame-opacity = 1.0;
inactive-opacity-override = false;
active-opacity = 1;
blur-background = true
blur-method = "dual_kawase";
blur-strength = 9;
blur-whitelist = false;
backend = "glx";
vsync = true;
log-level = "info";
shadow = false;
shadow-offset-x = -32;
shadow-offset-y = -4;
shadow-radius = 32
